DELETE http://localhost:3001/api/notes/63d9b219d3108c0e9ff754a3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZDJkNTUzMzg4NzY5YjA2MWEwZTFhMSIsInVzZXJOYW1lIjoiTWF0UUYiLCJpYXQiOjE2NzQ3NjM0MTcsImV4cCI6MTY3NTM2ODIxN30.Fzk2RptQyqH3XIaXgAyVqo2y0kSn7Hk2x67QitwNMd8