POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content": "creating note with user",
    "important": true,
    "userId": "63cbf4323633566dd361d607"
}

###

POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    
}
